server:
    port: 8573

#spring:
#    datasource:
#        druid:
#            driver-class-name: com.mysql.cj.Driver
#            url: jdbc:mysql://local host:3306/learn?serverTimezone=UTC
#            username: root
#            password: 123456
#spring:
#    datasource:
#        driver-class-name: com.mysql.cj.Driver
#        url: jdbc:mysql:mysql://local host:3306/onlinelearning?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#        username: root
#        password: 123456

spring:
    application:
        name: angry-food
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: ALWAYS
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/onlinelearning?useUnicode=true&characterEncoding=utf8
            username: root
            password: 123456
mybatis:
    config-location:
        - classpath:mybatis/mybatis-config.xml
    mapper-locations:
        - classpath:mappers/*.xml



